# Generated by Django 3.1.2 on 2020-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20201122_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicedojostudentbelt',
            unique_together={('studentService', 'belt')},
        ),
    ]
