# Generated by Django 3.1.2 on 2020-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_auto_20201122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofBirth',
            field=models.DateField(default='01/01/1901'),
        ),
    ]
