# Generated by Django 3.1.2 on 2020-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_auto_20201122_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completeName',
            field=models.CharField(default='', max_length=70),
        ),
    ]
