# Generated by Django 3.1.2 on 2020-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_user_completename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completeName',
            field=models.CharField(default='Complete Name', max_length=70),
        ),
    ]
