# Generated by Django 3.1.2 on 2020-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_auto_20201204_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completeName',
            field=models.CharField(default='', max_length=70),
        ),
    ]
