# Generated by Django 3.1.2 on 2020-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_auto_20201204_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedojostudentbelt',
            name='examDate',
            field=models.DateField(blank=True),
        ),
    ]
